[package]
name = "rnasm-report"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rnasm-span = { path = "../rnasm-span" }
unicode-width = "0.1.10"
