use std::collections::HashMap;
use super::Instruction;
use super::Mnemonic::*;
use super::AddrMode::*;
use once_cell::sync::Lazy;

#[derive(Debug, PartialEq, Eq, Clone, Copy, Hash)]
pub struct OpcodeInfo {
    pub byte: u8,
    pub len:  u16,
}

impl OpcodeInfo {
    fn new(byte: u8, len: u16) -> OpcodeInfo {
        OpcodeInfo { byte, len }
    }
}

pub static INST_TO_OPCODE: Lazy<HashMap<Instruction, OpcodeInfo>> = Lazy::new(|| {
    HashMap::from([
        (Instruction::new(Adc, Immediate(0)), OpcodeInfo::new(0x69, 2)),
        (Instruction::new(Adc, ZeroPage(0)),  OpcodeInfo::new(0x65, 2)),
        (Instruction::new(Adc, ZeroPageX(0)), OpcodeInfo::new(0x75, 2)),
        (Instruction::new(Adc, Absolute(0)),  OpcodeInfo::new(0x6D, 3)),
        (Instruction::new(Adc, AbsoluteX(0)), OpcodeInfo::new(0x7D, 3)),
        (Instruction::new(Adc, AbsoluteY(0)), OpcodeInfo::new(0x79, 3)),
        (Instruction::new(Adc, IndirectX(0)), OpcodeInfo::new(0x61, 2)),
        (Instruction::new(Adc, IndirectY(0)), OpcodeInfo::new(0x71, 2)),
        (Instruction::new(And, Immediate(0)), OpcodeInfo::new(0x29, 2)),
        (Instruction::new(And, ZeroPage(0)),  OpcodeInfo::new(0x25, 2)),
        (Instruction::new(And, ZeroPageX(0)), OpcodeInfo::new(0x35, 2)),
        (Instruction::new(And, Absolute(0)),  OpcodeInfo::new(0x2D, 3)),
        (Instruction::new(And, AbsoluteX(0)), OpcodeInfo::new(0x3D, 3)),
        (Instruction::new(And, AbsoluteY(0)), OpcodeInfo::new(0x39, 3)),
        (Instruction::new(And, IndirectX(0)), OpcodeInfo::new(0x21, 2)),
        (Instruction::new(And, IndirectY(0)), OpcodeInfo::new(0x31, 2)),
        (Instruction::new(Asl, Accumulator),  OpcodeInfo::new(0x0A, 1)),
        (Instruction::new(Asl, ZeroPage(0)),  OpcodeInfo::new(0x06, 2)),
        (Instruction::new(Asl, ZeroPageX(0)), OpcodeInfo::new(0x16, 2)),
        (Instruction::new(Asl, Absolute(0)),  OpcodeInfo::new(0x0E, 3)),
        (Instruction::new(Asl, AbsoluteX(0)), OpcodeInfo::new(0x1E, 3)),
        (Instruction::new(Bcc, Relative(0)),  OpcodeInfo::new(0x90, 2)),
        (Instruction::new(Bcs, Relative(0)),  OpcodeInfo::new(0xB0, 2)),
        (Instruction::new(Beq, Relative(0)),  OpcodeInfo::new(0xF0, 2)),
        (Instruction::new(Bit, ZeroPage(0)),  OpcodeInfo::new(0x24, 2)),
        (Instruction::new(Bit, Absolute(0)),  OpcodeInfo::new(0x2C, 3)),
        (Instruction::new(Bmi, Relative(0)),  OpcodeInfo::new(0x30, 2)),
        (Instruction::new(Bne, Relative(0)),  OpcodeInfo::new(0xD0, 2)),
        (Instruction::new(Bpl, Relative(0)),  OpcodeInfo::new(0x10, 2)),
        (Instruction::new(Brk, Implied),      OpcodeInfo::new(0x00, 1)),
        (Instruction::new(Bvc, Relative(0)),  OpcodeInfo::new(0x50, 2)),
        (Instruction::new(Bvs, Relative(0)),  OpcodeInfo::new(0x70, 2)),
        (Instruction::new(Clc, Implied),      OpcodeInfo::new(0x18, 1)),
        (Instruction::new(Cld, Implied),      OpcodeInfo::new(0xD8, 1)),
        (Instruction::new(Cli, Implied),      OpcodeInfo::new(0x58, 1)),
        (Instruction::new(Clv, Implied),      OpcodeInfo::new(0xB8, 1)),
        (Instruction::new(Cmp, Immediate(0)), OpcodeInfo::new(0xC9, 2)),
        (Instruction::new(Cmp, ZeroPage(0)),  OpcodeInfo::new(0xC5, 2)),
        (Instruction::new(Cmp, ZeroPageX(0)), OpcodeInfo::new(0xD5, 2)),
        (Instruction::new(Cmp, Absolute(0)),  OpcodeInfo::new(0xCD, 3)),
        (Instruction::new(Cmp, AbsoluteX(0)), OpcodeInfo::new(0xDD, 3)),
        (Instruction::new(Cmp, AbsoluteY(0)), OpcodeInfo::new(0xD9, 3)),
        (Instruction::new(Cmp, IndirectX(0)), OpcodeInfo::new(0xC1, 2)),
        (Instruction::new(Cmp, IndirectY(0)), OpcodeInfo::new(0xD1, 2)),
        (Instruction::new(Cpx, Immediate(0)), OpcodeInfo::new(0xE0, 2)),
        (Instruction::new(Cpx, ZeroPage(0)),  OpcodeInfo::new(0xE4, 2)),
        (Instruction::new(Cpx, Absolute(0)),  OpcodeInfo::new(0xEC, 3)),
        (Instruction::new(Cpy, Immediate(0)), OpcodeInfo::new(0xC0, 2)),
        (Instruction::new(Cpy, ZeroPage(0)),  OpcodeInfo::new(0xC4, 2)),
        (Instruction::new(Cpy, Absolute(0)),  OpcodeInfo::new(0xCC, 3)),
        (Instruction::new(Dec, ZeroPage(0)),  OpcodeInfo::new(0xC6, 2)),
        (Instruction::new(Dec, ZeroPageX(0)), OpcodeInfo::new(0xD6, 2)),
        (Instruction::new(Dec, Absolute(0)),  OpcodeInfo::new(0xCE, 3)),
        (Instruction::new(Dec, AbsoluteX(0)), OpcodeInfo::new(0xDE, 3)),
        (Instruction::new(Dex, Implied),      OpcodeInfo::new(0xCA, 1)),
        (Instruction::new(Dey, Implied),      OpcodeInfo::new(0x88, 1)),
        (Instruction::new(Eor, Immediate(0)), OpcodeInfo::new(0x49, 2)),
        (Instruction::new(Eor, ZeroPage(0)),  OpcodeInfo::new(0x45, 2)),
        (Instruction::new(Eor, ZeroPageX(0)), OpcodeInfo::new(0x55, 2)),
        (Instruction::new(Eor, Absolute(0)),  OpcodeInfo::new(0x4D, 3)),
        (Instruction::new(Eor, AbsoluteX(0)), OpcodeInfo::new(0x5D, 3)),
        (Instruction::new(Eor, AbsoluteY(0)), OpcodeInfo::new(0x59, 3)),
        (Instruction::new(Eor, IndirectX(0)), OpcodeInfo::new(0x41, 2)),
        (Instruction::new(Eor, IndirectY(0)), OpcodeInfo::new(0x51, 2)),
        (Instruction::new(Inc, ZeroPage(0)),  OpcodeInfo::new(0xE6, 2)),
        (Instruction::new(Inc, ZeroPageX(0)), OpcodeInfo::new(0xF6, 2)),
        (Instruction::new(Inc, Absolute(0)),  OpcodeInfo::new(0xEE, 3)),
        (Instruction::new(Inc, AbsoluteX(0)), OpcodeInfo::new(0xFE, 3)),
        (Instruction::new(Inx, Implied),      OpcodeInfo::new(0xE8, 1)),
        (Instruction::new(Iny, Implied),      OpcodeInfo::new(0xC8, 1)),
        (Instruction::new(Jmp, Absolute(0)),  OpcodeInfo::new(0x4C, 3)),
        (Instruction::new(Jmp, Indirect(0)),  OpcodeInfo::new(0x6C, 3)),
        (Instruction::new(Jsr, Absolute(0)),  OpcodeInfo::new(0x20, 3)),
        (Instruction::new(Lda, Immediate(0)), OpcodeInfo::new(0xA9, 2)),
        (Instruction::new(Lda, ZeroPage(0)),  OpcodeInfo::new(0xA5, 2)),
        (Instruction::new(Lda, ZeroPageX(0)), OpcodeInfo::new(0xB5, 2)),
        (Instruction::new(Lda, Absolute(0)),  OpcodeInfo::new(0xAD, 3)),
        (Instruction::new(Lda, AbsoluteX(0)), OpcodeInfo::new(0xBD, 3)),
        (Instruction::new(Lda, AbsoluteY(0)), OpcodeInfo::new(0xB9, 3)),
        (Instruction::new(Lda, IndirectX(0)), OpcodeInfo::new(0xA1, 2)),
        (Instruction::new(Lda, IndirectY(0)), OpcodeInfo::new(0xB1, 2)),
        (Instruction::new(Ldx, Immediate(0)), OpcodeInfo::new(0xA2, 2)),
        (Instruction::new(Ldx, ZeroPage(0)),  OpcodeInfo::new(0xA6, 2)),
        (Instruction::new(Ldx, ZeroPageY(0)), OpcodeInfo::new(0xB6, 2)),
        (Instruction::new(Ldx, Absolute(0)),  OpcodeInfo::new(0xAE, 3)),
        (Instruction::new(Ldx, AbsoluteY(0)), OpcodeInfo::new(0xBE, 3)),
        (Instruction::new(Ldy, Immediate(0)), OpcodeInfo::new(0xA0, 2)),
        (Instruction::new(Ldy, ZeroPage(0)),  OpcodeInfo::new(0xA4, 2)),
        (Instruction::new(Ldy, ZeroPageX(0)), OpcodeInfo::new(0xB4, 2)),
        (Instruction::new(Ldy, Absolute(0)),  OpcodeInfo::new(0xAC, 3)),
        (Instruction::new(Ldy, AbsoluteX(0)), OpcodeInfo::new(0xBC, 3)),
        (Instruction::new(Lsr, Accumulator),  OpcodeInfo::new(0x4A, 1)),
        (Instruction::new(Lsr, ZeroPage(0)),  OpcodeInfo::new(0x46, 2)),
        (Instruction::new(Lsr, ZeroPageX(0)), OpcodeInfo::new(0x56, 2)),
        (Instruction::new(Lsr, Absolute(0)),  OpcodeInfo::new(0x4E, 3)),
        (Instruction::new(Lsr, AbsoluteX(0)), OpcodeInfo::new(0x5E, 3)),
        (Instruction::new(Nop, Implied),      OpcodeInfo::new(0xEA, 1)),
        (Instruction::new(Ora, Immediate(0)), OpcodeInfo::new(0x09, 2)),
        (Instruction::new(Ora, ZeroPage(0)),  OpcodeInfo::new(0x05, 2)),
        (Instruction::new(Ora, ZeroPageX(0)), OpcodeInfo::new(0x15, 2)),
        (Instruction::new(Ora, Absolute(0)),  OpcodeInfo::new(0x0D, 3)),
        (Instruction::new(Ora, AbsoluteX(0)), OpcodeInfo::new(0x1D, 3)),
        (Instruction::new(Ora, AbsoluteY(0)), OpcodeInfo::new(0x19, 3)),
        (Instruction::new(Ora, IndirectX(0)), OpcodeInfo::new(0x01, 2)),
        (Instruction::new(Ora, IndirectY(0)), OpcodeInfo::new(0x11, 2)),
        (Instruction::new(Pha, Implied),      OpcodeInfo::new(0x48, 1)),
        (Instruction::new(Php, Implied),      OpcodeInfo::new(0x08, 1)),
        (Instruction::new(Pla, Implied),      OpcodeInfo::new(0x68, 1)),
        (Instruction::new(Plp, Implied),      OpcodeInfo::new(0x28, 1)),
        (Instruction::new(Rol, Accumulator),  OpcodeInfo::new(0x2A, 1)),
        (Instruction::new(Rol, ZeroPage(0)),  OpcodeInfo::new(0x26, 2)),
        (Instruction::new(Rol, ZeroPageX(0)), OpcodeInfo::new(0x36, 2)),
        (Instruction::new(Rol, Absolute(0)),  OpcodeInfo::new(0x2E, 3)),
        (Instruction::new(Rol, AbsoluteX(0)), OpcodeInfo::new(0x3E, 3)),
        (Instruction::new(Ror, Accumulator),  OpcodeInfo::new(0x6A, 1)),
        (Instruction::new(Ror, ZeroPage(0)),  OpcodeInfo::new(0x66, 2)),
        (Instruction::new(Ror, ZeroPageX(0)), OpcodeInfo::new(0x76, 2)),
        (Instruction::new(Ror, Absolute(0)),  OpcodeInfo::new(0x6E, 3)),
        (Instruction::new(Ror, AbsoluteX(0)), OpcodeInfo::new(0x7E, 3)),
        (Instruction::new(Rti, Implied),      OpcodeInfo::new(0x40, 1)),
        (Instruction::new(Rts, Implied),      OpcodeInfo::new(0x60, 1)),
        (Instruction::new(Sbc, Immediate(0)), OpcodeInfo::new(0xE9, 2)),
        (Instruction::new(Sbc, ZeroPage(0)),  OpcodeInfo::new(0xE5, 2)),
        (Instruction::new(Sbc, ZeroPageX(0)), OpcodeInfo::new(0xF5, 2)),
        (Instruction::new(Sbc, Absolute(0)),  OpcodeInfo::new(0xED, 3)),
        (Instruction::new(Sbc, AbsoluteX(0)), OpcodeInfo::new(0xFD, 3)),
        (Instruction::new(Sbc, AbsoluteY(0)), OpcodeInfo::new(0xF9, 3)),
        (Instruction::new(Sbc, IndirectX(0)), OpcodeInfo::new(0xE1, 2)),
        (Instruction::new(Sbc, IndirectY(0)), OpcodeInfo::new(0xF1, 2)),
        (Instruction::new(Sec, Implied),      OpcodeInfo::new(0x38, 1)),
        (Instruction::new(Sed, Implied),      OpcodeInfo::new(0xF8, 1)),
        (Instruction::new(Sei, Implied),      OpcodeInfo::new(0x78, 1)),
        (Instruction::new(Sta, ZeroPage(0)),  OpcodeInfo::new(0x85, 2)),
        (Instruction::new(Sta, ZeroPageX(0)), OpcodeInfo::new(0x95, 2)),
        (Instruction::new(Sta, Absolute(0)),  OpcodeInfo::new(0x8D, 3)),
        (Instruction::new(Sta, AbsoluteX(0)), OpcodeInfo::new(0x9D, 3)),
        (Instruction::new(Sta, AbsoluteY(0)), OpcodeInfo::new(0x99, 3)),
        (Instruction::new(Sta, IndirectX(0)), OpcodeInfo::new(0x81, 2)),
        (Instruction::new(Sta, IndirectY(0)), OpcodeInfo::new(0x91, 2)),
        (Instruction::new(Stx, ZeroPage(0)),  OpcodeInfo::new(0x86, 2)),
        (Instruction::new(Stx, ZeroPageY(0)), OpcodeInfo::new(0x96, 2)),
        (Instruction::new(Stx, Absolute(0)),  OpcodeInfo::new(0x8E, 3)),
        (Instruction::new(Sty, ZeroPage(0)),  OpcodeInfo::new(0x84, 2)),
        (Instruction::new(Sty, ZeroPageX(0)), OpcodeInfo::new(0x94, 2)),
        (Instruction::new(Sty, Absolute(0)),  OpcodeInfo::new(0x8C, 3)),
        (Instruction::new(Tax, Implied),      OpcodeInfo::new(0xAA, 1)),
        (Instruction::new(Tay, Implied),      OpcodeInfo::new(0xA8, 1)),
        (Instruction::new(Tsx, Implied),      OpcodeInfo::new(0xBA, 1)),
        (Instruction::new(Txa, Implied),      OpcodeInfo::new(0x8A, 1)),
        (Instruction::new(Txs, Implied),      OpcodeInfo::new(0x9A, 1)),
        (Instruction::new(Tya, Implied),      OpcodeInfo::new(0x98, 1)),
    ])
});
